=== medecins-du-monde/monitool/api/lib/resource/schema/input.json
{
	"$schema": "http://json-schema.org/schema#",
	"title": "Monitool input schema",
	"type": "object",
	"additionalProperties": false,
	"required": ["_id", "type", "project", "entity", "form", "period", "values"],
	"properties": {
		"_id":     {
			"type": "string",
			"pattern": "^[a-f\\d]{8}-([a-f\\d]{4}-){3}[a-f\\d]{12}:([a-f\\d]{8}-([a-f\\d]{4}-){3}[a-f\\d]{12}):[a-f\\d]{8}-([a-f\\d]{4}-){3}[a-f\\d]{12}:\\d{4}(\\-((S[1-2])|(Q[1-4])|(W\\d{2}\\-(sat|sun|mon))|(\\d{2}(\\-((W\\d{1}\\-(sat|sun|mon))|(\\d{2})))?)))?$$"
		},
		"_rev":    { "$ref": "#/definitions/revision" },
		"type":    { "type": "string", "pattern": "^input$" },
		"project": { "$ref": "#/definitions/uuid" },
		"entity":  {
			"type": "string",
			"pattern": "^[a-f\\d]{8}-([a-f\\d]{4}-){3}[a-f\\d]{12}$"
		},
		"form":    { "$ref": "#/definitions/uuid" },
		"period": {
			"type": "string",
			"pattern": "^\\d{4}(\\-((S[1-2])|(Q[1-4])|(W\\d{2}\\-(sat|sun|mon))|(\\d{2}(\\-((W\\d{1}\\-(sat|sun|mon))|(\\d{2})))?)))?$"
		},
		"values": {
			"type": "object",
			"additionalProperties": false,
			"patternProperties": {
				"[a-f\\d]{8}-([a-f\\d]{4}-){3}[a-f\\d]{12}": {
					"type": "array",
					"items": { "type": "number" },
					"minItems": 1
				}
			}
		}
	},

	"definitions": {
		"uuid": {
			"type": "string",
			"pattern": "^[a-f\\d]{8}-([a-f\\d]{4}-){3}[a-f\\d]{12}$"
		},
		"revision": {
			"type": "string",
			"pattern": "^[\\d]+\\-[\\da-f]{32}$"
		}
	}
}

=== medecins-du-monde/monitool/test/data/input.json
{
	"_id": "624c94fa-9ebc-4f8b-8389-f5959149a0a7:0c243e08-8c21-4946-9f5f-ce255106901b:8a7980f8-0e47-49bb-bf54-fdbe2013e3ea:2010-02",
	"type": "input",
	"project": "624c94fa-9ebc-4f8b-8389-f5959149a0a7",
	"entity": "0c243e08-8c21-4946-9f5f-ce255106901b",
	"form": "8a7980f8-0e47-49bb-bf54-fdbe2013e3ea",
	"period": "2010-02",
	"values": {
		"c0cdae8e-4ebb-41e3-a68e-d8247d3ca7ce": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
		"a83cda13-fbc7-477d-b158-33077a243c81": [1]
	}
}
