=== medecins-du-monde/monitool/server/lib/config-schema.json
{
	"$schema": "http://json-schema.org/schema#",
	"title": "Monitool configuration file schema",

	"type": "object",
	"additionalProperties": false,
	"required": ["debug", "baseUrl", "port", "cookieSecret", "couchdb", "auth", "api"],
	"properties": {
		"debug": {
			"type": "boolean"
		},
		"baseUrl": {
			"type": "string",
			"pattern": "^https?://[a-z\\d\\.\\-]+(:\\d+)?$"
		},
		"port": {
			"type": "integer",
			"minimum": 1,
			"maximum": 65536
		},
		"cookieSecret": {
			"type": "string",
			"minimum": 6
		},
		"couchdb": {
			"type": "object",
			"required": ["host", "port", "bucket", "sessionBucket"],
			"properties": {
				"host": {"type": "string"},
				"port": {
					"type": "integer",
					"minimum": 1,
					"maximum": 65536
				},
				"bucket": {
					"type": "string",
					"minLength": 1
				},
				"sessionBucket": {
					"type": "string",
					"minLength": 1
				},
				"username": {"type": "string"},
				"password": {"type": "string"}
			}
		},
		"api": {
			"type": "object",
			"properties": {
				"google": {"type": "string"}
			}
		},
		"auth": {
			"type": "object",
			"required": ["administrator", "providers"],
			"properties": {
				"administrator": {
					"type": "string",
					"minLength": 1
				},

				"providers": {
					"type": "object",
					"required": [],
					"properties": {
						"azureAD": {
							"type": "object",
							"required": ["label", "domain", "clientId", "clientSecret"],
							"properties": {
								"label": {"type": "string", "minLength": 1},
								"domain": {"type": "string", "minLength": 1},
								"clientId": {"type": "string", "minLength": 1},
								"clientSecret": {"type": "string", "minLength": 1}
							}
						},
						"training": {
							"type": "object",
							"required": ["label", "account"],
							"properties": {
								"label": {"type": "string", "minLength": 1},
								"account": {"type": "string", "minLength": 1}
							}
						}
					}
				}
			}
		}
	}
}

=== medecins-du-monde/monitool/server/config-template.json
{
	"debug": true,
	"baseUrl": "http://localhost:8000",
	"port": 8000,
	"cookieSecret": "abcdef",
	"couchdb": {
		"host": "localhost",
		"port": 5984,
		"bucket": "monitool",
		"sessionBucket": "monitool-sessions",
		"username": "",
		"password": ""
	},
	"api": {
		"google": "[enter google translate api key here]"
	},
	"auth": {
		"administrator": "romain.gilliotte",
		"providers": {
			"azureAD": {
				"label": "Use MDM account",
				"domain": "medecinsdumonde.net",
				"clientId": "[enter client id]",
				"clientSecret": "[enter client secret]"
			},
			"training": {
				"label": "Use training account (admin)",
				"account": "romain.gilliotte"
			}
		}
	}
}
